const trafficSections = {
    "MP ŠENTILJ - POČIVALIŠČE ŠENTILJ": "Maribor",
    "POČIVALIŠČE ŠENTILJ - ŠENTILJ": "Maribor",
    "PRIKLJ.ŠENTILJ S": "Maribor",
    "PESNICA - DRAGUČOVA": "Maribor",
    "DRAGUČOVA - MB (ZRKOVSKA)": "Maribor",
    "MB (ZRKOVSKA)  - MB (PTUJSKA)": "Maribor",
    "MB (PTUJSKA) - ROGOZA": "Maribor",
    "ROGOZA - SLIVNICA": "Maribor",
    "SLIVNICA": "Maribor",
    "SLIVNICA - FRAM": "Maribor",
    "PRIKLJ. FRAM  -  MB": "Maribor",
    "PRIKLJ. FRAM -  CE": "Celje",
    "FRAM - SL.BISTRICA-SEVER": "Slovenska Bistrica",
    "SL.BISTRICA - SEVER-JUG": "Slovenska Bistrica",
    "PRIKLJ. SL. BISTRICA J. - MB": "Maribor",
    "PRIKLJ. SL. BISTRICA J - CE": "Celje",
    "SL.BISTRICA - SL.KONJICE": "Slovenska Bistrica",
    "PRIKLJ. SL. KONJICE - MB": "Maribor",
    "PRIKLJ. SL. KONJICE - CE": "Celje",
    "SL.KONJICE - DRAMLJE": "Celje",
    "PRIKLJ. DRAMLJE - MB": "Maribor",
    "PRIKLJ. DRAMLJE - CE": "Celje",
    "DRAMLJE - LJUBEČNA": "Celje",
    "LJUBEČNA - CELJE": "Celje",
    "CELJE - CELJE ZAHOD": "Celje",
    "CELJE ZAHOD - ARJA VAS": "Celje",
    "ARJA VAS - ŠEMPETER": "Celje",
    "ŠEMPETER - ŠENTRUPERT": "Celje",
    "VRANSKO - TROJANE": "Celje",
    "TROJANE  -  BLAGOVICA": "Domžale",
    "PRIKLJ.BLAGOVICA - CE": "Celje",
    "PRIKLJ. BLAGOVICA - LJ": "Ljubljana",
    "BLAGOVICA - LUKOVICA": "Domžale",
    "LUKOVICA - KRTINA": "Domžale",
    "PRIKLJ. LUKOVICA ": "Domžale",
    "PRIKLJ. KRTINA": "Domžale",
    "KRTINA - DOMŽALE": "Domžale",
    "DOMŽALE - ŠENTJAKOB": "Ljubljana",
    "ŠENTJAKOB - SNEBERJE": "Ljubljana",
    "SNEBERJE - LJ (ZADOBRAVA)": "Ljubljana",
    "LJ (ZADOBRAVA) - R LJ ZADOBROVA": "Ljubljana",
    "RAZCEP LJ ZADOBROVA": "Ljubljana",
    "R LJ ZADOBROVA - IND. CONA MOSTE": "Ljubljana",
    "LJ (IND. CONA MOSTE - ZALOŠKA)": "Ljubljana",
    "LJ (ZALOŠKA - LITIJSKA)": "Ljubljana",
    "LJ (LITIJSKA - MALENCE)": "Ljubljana",
    "RAZCEP LJ MALENCE": "Ljubljana",
    "LJ (MALENCE - DOLENJSKA C.)": "Ljubljana",
    "PRIKLJ. LJ J (DOLENJSKA C.)": "Ljubljana",
    "LJ (DOLENJSKA  -  PERUZIJEVA)": "Ljubljana",
    "LJ (PERUZIJEVA - BARJANSKA)": "Ljubljana",
    "LJ (BARJANSKA  -  VIČ)": "Ljubljana",
    "LJ (VIČ  -  KOZARJE)": "Ljubljana",
    "LJ ( KOZARJE - RAZEP KOZARJE)": "Ljubljana",
    "LJ (RAZEP KOZARJE) - BREZOVICA": "Ljubljana",
    "BREZOVICA - VRHNIKA": "Vrhnika",
    "PRIKLJ. VRHNIKA - LJ": "Ljubljana",
    "PRIKLJ. VRHNIKA - KP": "Koper",
    "VRHNIKA - LOGATEC": "Vrhnika",
    "PRIKLJ. LOGATEC": "Logatec",
    "LOGATEC - UNEC": "Logatec",
    "PRIKLJ. UNEC - LJ": "Ljubljana",
    "PRIKLJ. UNEC - KP": "Koper",
    "UNEC - POSTOJNA": "Postojna",
    "PRIKLJ. POSTOJNA - LJ": "Ljubljana",
    "PRIKLJ. POSTOJNA - KP": "Koper",
    "POSTOJNA - RAZDRTO": "Postojna",
    "RAZDRTO - NANOS": "Postojna",
    "PRIKLJ. RAZDRTO - LJ": "Ljubljana",
    "PRIKLJ. RAZDRTO - KP": "Koper",
    "RAZCEP NANOS": "Postojna",
    "NANOS  -  SENOŽEČE": "Postojna",
    "PRIKLJ. SENOŽEČE ": "Postojna",
    "SENOŽEČE  -   GABRK": "Postojna",
    "GABRK  -  DIVAČA": "Postojna",
    "PRIKLJ. DIVAČA": "Postojna",
    "DIVAČA - KOZINA": "Koper",
    "PRIKLJ. KOZINA - LJ": "Ljubljana",
    "PRIKLJ. KOZINA - KP": "Koper",
    "KOZINA - KASTELEC": "Koper",
    "KASTELEC - ČRNI KAL": "Koper",
    "ČRNI KAL  -  RAZCEP SERMIN": "Koper",
    "RAZCEP SERMIN  -  H5": "Koper",
    "MP KARAVANKE - HRUŠICA": "Jesenice",
    "HRUŠICA - LIPCE": "Jesenice",
    "LIPCE - LESCE": "Jesenice",
    "PRIKLJ. LESCE - JESENICE": "Jesenice",
    "PRIKLJ. LESCE - KRANJ": "Kranj",
    "LESCE - RADOVLJICA": "Radovljica",
    "RADOVLJICA - BREZJE": "Radovljica",
    "BREZJE - PODTABOR": "Radovljica",
    "PODTABOR - NAKLO": "Kranj",
    "NAKLO - KRANJ Z": "Kranj",
    "KRANJ Z - KRANJ V": "Kranj",
    "KRANJ V  -  BRNIK": "Kranj",
    "BRNIK  -  VODICE": "Ljubljana",
    "VODICE  - LJ ( ŠMARTNO)": "Ljubljana",
    "LJ (ŠMARTNO  -   BROD)": "Ljubljana",
    "LJ (BROD - ŠENTVID)": "Ljubljana",
    "LJ (ŠENTVID - PODUTIK)": "Ljubljana",
    "LJ (PODUTIK - KOSEZE)": "Ljubljana",
    "RAZCEP KOSEZE": "Ljubljana",
    "RAZCEP KOSEZE - KOSEZE ": "Ljubljana",
    "LJ (KOSEZE  -  BRDO)": "Ljubljana",
    "LJ (BRDO  -  KOZARJE)": "Ljubljana",
    "LJ (KOZARJE) - RAZCEP KOZARJE": "Ljubljana",
    "RAZCEP LJ KOZARJE": "Ljubljana",
    "LJ (MALENCE)  -  RAZCEP MALENCE": "Ljubljana",
    "RAZCEP MALENCE  -  ŠMARJE-SAP": "Ljubljana",
    "ŠMARJE SAP - CIKAVA": "Grosuplje",
    "CIKAVA - GROSUPLJE": "Grosuplje",
    "GROSUPLJE - VIŠNJA GORA": "Grosuplje",
    "VIŠNJA GORA - IVANČNA GORICA": "Ivančna Gorica",
    "IVANČNA GORICA - BIČ": "Ivančna Gorica",
    "BIČ - TREBNJE Z": "Trebnje",
    "TREBNJE Z - TREBNJE V": "Trebnje",
    "TREBNJE V - PRIKLJ. MIRNA PEČ": "Novo Mesto",
    "PRIKLJ. MIRNA PEČ  -  NM PRIKLJ. Z": "Novo Mesto",
    "NM PRIKLJ. Z - NM PRIKLJ. V": "Novo Mesto",
    "NM PRIKLJ.V - KRONOVO": "Novo Mesto",
    "KRONOVO - DOBRUŠKA VAS": "Novo Mesto",
    "DOBRUŠKA VAS  -  SMEDNIK": "Krško",
    "SMEDNIK   -  DRNOVO": "Krško",
    "PRIKLJ. DRNOVO - NM": "Novo Mesto",
    "PRIKLJ. DRNOVO - ČATEŽ": "Brežice",
    "DRNOVO  -  BREŽICE": "Brežice",
    "BREŽICE - PRIKLJ. OBREŽJE": "Brežice",
    "PRIKLJ. OBREŽJE  - OBREŽJE TERMINAL": "Brežice",
    "OBREŽJE TERMINAL - MP OBREŽJE": "Brežice",
    "GABRK - SEŽANA V": "Sežana",
    "SEŽANA V - SEŽANA Z": "Sežana",
    "SEŽANA Z  -  FERNETIČI": "Sežana",
    "FERNETIČI - MP FERNETIČI": "Sežana",
    "PRIKLJ. FERNETIČI": "Sežana",
    "SLIVNICA - LETALIŠČE MB": "Maribor",
    "LETALIŠČE MB - MARJETA": "Maribor",
    "MARJETA - ZLATOLIČJE": "Maribor",
    "ZLATOLIČJE - HAJDINA": "Ptuj",
    "HAJDINA - DRAŽENCI": "Ptuj",
    "DRAŽENCI -PODLEHNIK": "Ptuj",
    "PODLEHNIK - GRUŠKOVJE ": "Ptuj",
    "DRAGUČOVA - PERNICA": "Maribor",
    "PERNICA - LENART": "Maribor",
    "PRIKLJ.PERNICA - MB": "Maribor",
    "PRIKLJ.PERNICA - MS": "Murska Sobota",
    "LENART - SV.TROJICA": "Maribor",
    "SV. TROJICA - PRIKLJ. CERKVENJAK": "Maribor",
    "PRIKLJ. CERKVENJAK - SV. JURIJ OB ŠČAVNICI": "Murska Sobota",
    "SV.JURIJ OB ŠČAVNICI - VUČJA VAS": "Murska Sobota",
    "PRIKLJ. VUČJA VAS - MB": "Maribor",
    "PRIKLJ. VUČJA VAS  - MS": "Murska Sobota",
    "VUČJA VAS - MURSKA SOBOTA": "Murska Sobota",
    "PRIKLJ. MURSKA SOBOTA - MB": "Maribor",
    "PRIKLJ. MURSKA SOBOTA - LENDAVA": "Lendava",
    "MURSKA SOBOTA - LIPOVCI": "Murska Sobota",
    "LIPOVCI - GANČANI": "Murska Sobota",
    "GANČANI - TURNIŠČE": "Murska Sobota",
    "TURNIŠČE - DOLGA VAS": "Lendava",
    "DOLGA VAS - LENDAVA": "Lendava",
    "PRIKLJ. LENDAVA - MS": "Murska Sobota",
    "PRIKLJ. LENDAVA - PINCE": "Lendava",
    "LENDAVA - PINCE": "Lendava",
    "PINCE - MP PINCE": "Lendava",
    "LJ (ZADOBROVA  - LESKOVŠKOVA C.)": "Ljubljana",
    "LJ (LESKOŠKOVA C. - ŠMARTINSKA)": "Ljubljana",
    "LJ (ŠMARTINSKA - TOMAČEVO)": "Ljubljana",
    "LJ (TOMAČEVO  -  DUNAJSKA)": "Ljubljana",
    "LJ (DUNAJSKA - SAVLJE)": "Ljubljana",
    "LJ (SAVLJE - IND. CONA ŠIŠKA)": "Ljubljana",
    "LJ (IND. CONA ŠIŠKA - CELOVŠKA)": "Ljubljana",
    "LJ (CELOVŠKA  -  VODNIKOVA)": "Ljubljana",
    "LJ (VODNIKOVA  -  PODUTIK)": "Ljubljana",
    "LJ (PODUTIK - KOSEZE)": "Ljubljana",
    "NANOS - (RAZDRTO) - PODNANOS - VIPAVA": "Vipava",
    "PRIKLJ. VIPAVA": "Vipava",
    "VIPAVA - AJDOVŠČINA": "Ajdovščina",
    "AJDOVŠČINA - SELO": "Ajdovščina",
    "PRIKLJ. SELO - AJDOVŠČINA": "Ajdovščina",
    "PRIKLJ.SELO - VRTOJBA": "Šempeter pri Gorici",
    "SELO  -  VOGRSKO": "Nova Gorica",
    "VOGRSKO - ŠEMPETER": "Šempeter pri Gorici",
    "ŠEMPETER - VRTOJBA": "Šempeter pri Gorici",
    "VRTOJBA - MP VRTOJBA": "Šempeter pri Gorici",
    "MP ŠKOFIJE  -  PLAVJE": "Koper",
    "PLAVJE - ŠKOFIJE": "Koper",
    "ŠKOFIJE - PRIKLJ. SRMIN": "Koper",
    "PRIKLJ. SRMIN - SRMIN (A1)": "Koper",
    "PRIKLJUČEK PLAVJE - KP": "Koper",
    "PRIKLJUČEK PLAVJE - MP": "Koper",
    "SERMIN - BERTOKI": "Koper",
    "BERTOKI - KP(ŠKOCJAN)": "Koper",
    "KOPER (SLAVČEK - SEMEDELA)": "Koper",
    "KOPER (SEMEDELA) - IZOLA": "Izola",
    "A5 - DOLGA VAS": "Lendava",
    "DOLGA VAS - RONDO DOLGA VAS": "Lendava",
    "MP VIČ - DRAVOGRAD": "Dravograd",
    "DRAVOGRAD - RADLJE": "Dravograd",
    "RADLJE ": "Radlje ob Dravi",
    "RADLJE - BREZNO": "Radlje ob Dravi",
    "BREZNO - RUTA": "Velenje",
    "RUTA - SELNICA": "Maribor",
    "SELNICA - MB(OTOK)": "Maribor",
    "MB (OTOK) - MB (KOROŠKI MOST)": "Maribor",
    "MB (KOR. MOST - C. PROLE. BRIGAD)": "Maribor",
    "MB (C. PROLE. BRIGAD  -  TRŽAŠKA C.)": "Maribor",
    "MB (TRŽAŠKA) - MIKLAVŽ": "Maribor",
    "SL.BISTRICA - PRAGERSKO": "Slovenska Bistrica",
    "PRAGERSKO - ŠIKOLE": "Ptuj",
    "ŠIKOLE - KIDRIČEVO": "Ptuj",
    "KIDRIČEVO - HAJDINA": "Ptuj",
    "PTUJ(TURNIŠČE - BUDINA)": "Ptuj",
    "PTUJ - SPUHLJA": "Ptuj",
    "SPUHLJA - GORIŠNICA": "Ptuj",
    "GORIŠNICA - ORMOŽ": "Ormož",
    "ORMOŽ Z  -  ORMOŽ V": "Ormož",
    "ORMOŽ - SREDIŠČE OB DRAVI": "Ormož",
    "SREDIŠČE OB DRAVI  -  MP SRED.": "Ormož",
    "DRAVOGRAD - OTIŠKI VRH": "Dravograd",
    "OTIŠKI VRH - SL.GRADEC": "Slovenj Gradec",
    "SL.GRADEC ": "Slovenj Gradec",
    "SL.GRADEC - LUŽNIK": "Slovenj Gradec",
    "LUŽNIK - GORNJI DOLIČ": "Slovenj Gradec",
    "GORNJI DOLIČ - VELENJE": "Velenje",
    "VELENJE - ČRNOVA": "Velenje",
    "ČRNOVA - ARJA VAS": "Celje",
    "PRIKLJ. CELJE Z - MEDLOG": "Celje",
    "MEDLOG - CELJE": "Celje",
    "CELJE - CE(POLULE)": "Celje",
    "CE (POLULE) - LAŠKO": "Laško",
    "LAŠKO - ŠMARJETA": "Laško",
    "ŠMARJETA - RIMSKE TOPLICE": "Laško",
    "RIM.TOPLICE - ZIDANI MOST": "Laško",
    "ZIDANI MOST - RADEČE": "Radeče",
    "RADEČE ": "Radeče",
    "RADEČE - BOŠTANJ": "Sevnica",
    "BOŠTANJ": "Sevnica",
    "BOŠTANJ - IMPOLJCA": "Sevnica",
    "IMPOLJCA - BRESTANICA": "Krško",
    "BRESTANICA - KRŠKO": "Krško",
    "KRŠKO - LESKOVEC": "Krško",
    "LESKOVEC - DRNOVO": "Krško",
    "POSTOJNA - PIVKA": "Postojna",
    "PIVKA - RIBNICA": "Pivka",
    "RIBNICA - PREM": "Ilirska Bistrica",
    "PREM - IL.BISTRICA": "Ilirska Bistrica",
    "ILIRSKA BISTRICA (NIKOLA TESLA)": "Ilirska Bistrica",
    "IL.BISTRICA - DOLNJI ZEMON": "Ilirska Bistrica",
    "DOLNJI ZEMON  -  MP JELŠANE": "Ilirska Bistrica",
    "MP STAROD - PODGRAD": "Ilirska Bistrica",
    "PODGRAD - OBROV": "Koper",
    "OBROV - KOZINA": "Koper",
    "KOZINA - MP KOZINA": "Koper",
    "LJ(ŠENTVID  -  OBVOZNICA)": "Ljubljana",
    "PODLEHNIK-GRUŠKOVJE": "Ptuj",
    "KOPER - ŠMARJE": "Koper",
    "ŠMARJE - DRAGONJA": "Koper",
    "DRAGONJA - MP DRAGONJA": "Koper",
    "SLAVČEK -  KOPER": "Koper",
    "KOPER - ŠKOCJANSKI ZATOK": "Koper",
    "ŠKOCJANSKI ZATOK - LUKA KOPER": "Koper",
    "MP LJUBELJ - BISTRICA(TRŽIČ)": "Tržič",
    "BISTRICA(TRŽIČ) - ZVIRČE": "Tržič",
    "ZVIRČE - PODTABOR": "Tržič",
    "MP ROBIČ - ROBIČ": "Kobarid",
    "ROBIČ - STARO SELO": "Kobarid",
    "STARO SELO - KOBARID": "Kobarid",
    "KOBARID - IDRSKO": "Kobarid",
    "IDRSKO - PERŠETI": "Kobarid",
    "PERŠETI - MOST NA SOČI": "Tolmin",
    "MOST NA SOČI - BAČA": "Tolmin",
    "BAČA - DOL. TREBUŠA": "Tolmin",
    "DOL TREBUŠA - ŽELIN": "Idrija",
    "ŽELIN - SP. IDRIJA(MAROF)": "Idrija",
    "SP. IDRIJA": "Idrija",
    "SP. IDRIJA - GODOVIČ": "Idrija",
    "GODOVIČ - KALCE": "Logatec",
    "KALCE - LOGATEC": "Logatec",
    "LOGATEC - PRIKLJ. LOGATEC": "Logatec",
    "PERŠETI - UŠNIK": "Nova Gorica",
    "UŠNIK - KANAL": "Nova Gorica",
    "KANAL - PLAVE": "Nova Gorica",
    "PLAVE - SOLKAN": "Nova Gorica",
    "SOLKAN-NOVA GORICA (KROMBERK)": "Nova Gorica",
    "KROMBERK  -  ROŽNA DOLINA": "Nova Gorica",
    "NG(R. DOLINA)  -  ŠEMPETER": "Nova Gorica",
    "KRANJ - LETALIŠČE BRNIK": "Kranj",
    "LETALIŠČE BRNIK - SP.BRNIK": "Kranj",
    "SP.BRNIK - MOSTE": "Ljubljana",
    "MOSTE - MENGEŠ": "Mengeš",
    "MENGEŠ (SLOVENSKA C.) ": "Mengeš",
    "MENGEŠ (KAMNIŠKA C. - KOLODVORSKA C.) ": "Mengeš",
    "MENGEŠ (KOLODVORSKA C.) - LOKA": "Mengeš",
    "LOKA - TRZIN": "Trzin",
    "TRZIN - LJ(ČRNUČE)": "Ljubljana",
    "LJ (ČRNUČE - BRNČIČEVA)": "Ljubljana",
    "LJ (BRNČIČEVA - TOMAČEVO)": "Ljubljana",
    "NOVO MESTO (AC - LOČNA)": "Novo Mesto",
    "NOVO MESTO (LOČNA - KRKA)": "Novo Mesto",
    "NOVO MESTO (KRKA) ": "Novo Mesto",
    "NOVO MESTO (KRKA - REVOZ)": "Novo Mesto",
    "NOVO MESTO (REVOZ) - METLIKA": "Novo Mesto",
    "METLIKA - MP METLIKA": "Metlika",
    "LJ (RUDNIK) - ŠKOFLJICA": "Ljubljana",
    "ŠKOFLJICA": "Škofljica",
    "ŠKOFLJICA - RAŠICA": "Škofljica",
    "RAŠICA - ŽLEBIČ": "Škofljica",
    "ŽLEBIČ - BREG": "Ribnica",
    "BREG - HROVAČA": "Ribnica",
    "HROVAČA - DOLENJA VAS": "Ribnica",
    "DOLENJA VAS - KOČEVJE": "Kočevje",
    "KOČEVJE ": "Kočevje",
    "KOČEVJE - LIVOLD": "Kočevje",
    "LIVOLD - ŠTALCERJI": "Kočevje",
    "ŠTALCERJI - FARA": "Kočevje",
    "FARA - PETRINA": "Kočevje",
    "PETRINA - MP PETRINA": "Kočevje",
    "ŠKOFLJICA - ŠMARJE SAP": "Škofljica",
    "CELJE - ŠTORE": "Celje",
    "ŠTORE -  ŠENTJUR": "Šentjur",
    "ŠENTJUR - ŠMARJE PRI JELŠAH": "Šentjur",
    "ŠMARJE PRI JELŠAH - MESTINJE": "Šmarje pri Jelšah",
    "MESTINJE - PODPLAT": "Rogaška Slatina",
    "PODPLAT - TEKAČEVO": "Rogaška Slatina",
    "TEKAČEVO  -  KOTEC": "Rogaška Slatina",
    "KOTEC - ROGATEC": "Rogatec",
    "ROGATEC - MP DOBOVEC": "Rogatec",
    "ČRNUČE - ŠENTJAKOB": "Ljubljana",
    "ŠENTJAKOB - DOLSKO": "Ljubljana",
    "DOLSKO - RIBČE": "Ljubljana",
    "RIBČE - LITIJA": "Litija",
    "LITIJA - ZAGORJE": "Litija",
    "ZAGORJE - TRBOVLJE": "Zagorje ob Savi",
    "TRBOVLJE - HRASTNIK": "Trbovlje",
    "HRASTNIK - ZIDANI MOST": "Hrastnik",
    "DOLGA VAS - MP DOLGA VAS": "Lendava",
    "LENDAVA - PETIŠOVCI": "Lendava",
    "PETIŠOVCI - MP PETIŠOVCI": "Lendava",
    "IZOLA - JAGODJE": "Izola",
    "JAGODJE-VALETA": "Izola",
    "VALETA - LUCIJA": "Portorož",
    "LUCIJA -  SEČOVLJE": "Portorož",
    "SEČOVLJE - MP SEČOVLJE": "Portorož",
    "MP HOLMEC - POLJANA": "Ravne na Koroškem",
    "POLJANA - PREVALJE": "Prevalje",
    "PREVALJE - RAVNE": "Ravne na Koroškem",
    "RAVNE - DRAVOGRAD": "Ravne na Koroškem",
    "MP KORENSKO SEDLO - PODKOREN": "Kranjska Gora",
    "PODKOREN - KR.GORA": "Kranjska Gora",
    "KR.GORA - GOZD MARTULJEK": "Kranjska Gora",
    "GOZD MARTULJEK - MOJSTRANA-DOVJE": "Kranjska Gora",
    "DOVJE - MOJSTRANA-KRAJE": "Kranjska Gora",
    "KRAJE - HRUŠICA": "Jesenice",
    "MP RATEČE - RATEČE": "Kranjska Gora",
    "RATEČE - PODKOREN": "Kranjska Gora",
    "MP PREDEL - KLUŽE": "Bovec",
    "KLUŽE - BOVEC": "Bovec",
    "BOVEC(PO OBVOZNICI) - ŽAGA": "Bovec",
    "ŽAGA - KOBARID": "Kobarid",
    "ŠEMPETER - VOLČJA DRAGA": "Nova Gorica",
    "VOLČJA DRAGA - DORNBERK": "Nova Gorica",
    "DORNBERK - ŠTANJEL": "Nova Gorica",
    "ŠTANJEL - DUTOVLJE": "Sežana",
    "DUTOVLJE - SEŽANA": "Sežana",
    "DIVAČA - LOKEV-LIPICA": "Sežana",
    "KRANJSKA GORA  -  ERIKA": "Kranjska Gora",
    "RUSKA CESTA (ERIKA - VRŠIČ)": "Kranjska Gora",
    "VRŠIČ - TRENTA": "Bovec",
    "TRENTA - BOVEC": "Bovec",
    "GODOVIČ - ČRNI VRH": "Idrija",
    "ČRNI VRH - COL": "Idrija",
    "COL - AJDOVŠČINA": "Ajdovščina",
    "ČRNI KAL  -  KORTINE": "Koper",
    "KORTINE - GRAČIŠČE": "Koper",
    "GRAČIŠČE - SOČERGA": "Koper",
    "SOČERGA  -  MP  SOČERGA": "Koper",
    "RIŽANA - KORTINE": "Koper",
    "LESCE - BLED": "Bled",
    "BLED - PRISTAVA": "Bled",
    "PRISTAVA - SOTESKA": "Bled",
    "SOTESKA - BITNJE": "Kranj",
    "BITNJE - BOH.BISTRICA": "Bohinj",
    "BOH.BISTRICA - JEZERO": "Bohinj",
    "MP ZG.JEZERSKO - ZG.JEZERSKO": "Jezersko",
    "ZG.JEZERSKO - SP.JEZERSKO": "Jezersko",
    "SP. JEZERSKO - PREDDVOR": "Preddvor",
    "PREDDVOR - KR(PRIMSKOVO)": "Kranj",
    "KR(PRIMSKOVO - LABORE)": "Kranj",
    "KRANJ - ŠKOFJA LOKA": "Kranj",
    "OBVOZNICA ŠKOFJA LOKA": "Škofja Loka",
    "ŠK.LOKA - GORENJA VAS": "Škofja Loka",
    "GORENJA VAS - TREBIJA": "Škofja Loka",
    "TREBIJA - SOVODENJ": "Škofja Loka",
    "SOVODENJ - CERKNO": "Cerkno",
    "CERKNO - ŽELIN": "Cerkno",
    "ŠKOFJA LOKA - JEPRCA": "Škofja Loka",
    "KR (LABORE) - JEPRCA": "Kranj",
    "JEPRCA - MEDVODE": "Medvode",
    "MEDVODE - STANEŽIČE": "Medvode",
    "STANEŽIČE  - LJ( ŠENTVID)": "Ljubljana",
    "PRIKLJUČEK UNEC-UNEC": "Unec",
    "UNEC - RAKEK": "Unec",
    "RAKEK - CERKNICA": "Cerknica",
    "CERKNICA - BL.POLICA": "Cerknica",
    "BL.POLICA - SODRAŽICA": "Sodražica",
    "SODRAŽICA - ŽLEBIČ": "Sodražica",
    "BLOŠKA POLICA - PUDOB": "Cerknica",
    "PUDOB - BABNO POLJE": "Cerknica",
    "KOČEVJE - STARI LOG": "Kočevje",
    "STARI LOG - DVOR": "Kočevje",
    "PRIKLJ. TREBNJE V - GRM": "Trebnje",
    "GRM - TREBNJE": "Trebnje",
    "TREBNJE (ODRGA - KAMNA GORA)": "Trebnje",
    "TREBNJE - MIRNA": "Trebnje",
    "MIRNA - MOKRONOG": "Trebnje",
    "MOKRONOG - BOŠTANJ": "Sevnica",
    "IVANČNA GORICA - KRKA": "Ivančna Gorica",
    "KRKA - ŽUŽEMBERK": "Žužemberk",
    "ŽUŽEMBERK - DVOR": "Žužemberk",
    "DVOR - SOTESKA": "Žužemberk",
    "SOTESKA - ČRMOŠNJICE": "Žužemberk",
    "ČRMOŠNJICE - RUČETNA VAS": "Črnomelj",
    "RUČETNA VAS - ČRNOMELJ": "Črnomelj",
    "LIVOLD - BREZOVICA": "Kočevje",
    "BREZOVICA - DOBLIČE": "Kočevje",
    "DOBLIČE - KANIŽARICA": "Kočevje",
    "METLIKA - PODZEMELJ": "Metlika",
    "PODZEMELJ - ČRNOMELJ": "Črnomelj",
    "ČRNOMELJ (ULICA MOŠA PIJADE - KOČEVJE)": "Črnomelj",
    "ČRNOMELJ (KOLODVORSKA - MOŠA PIJADE)": "Črnomelj",
    "ČRNOMELJ - (KOČEVJE) - KANIŽARICA": "Črnomelj",
    "KANIŽARICA - VINICA": "Črnomelj",
    "VINICA ": "Črnomelj",
    "VINICA - MOST ČEZ KOLPO": "Črnomelj",
    "SL.BISTRICA - POLJČANE": "Slovenska Bistrica",
    "POLJČANE ": "Poljčane",
    "POLJČANE - PODPLAT": "Poljčane",
    "MESTINJE - GOLOBINJEK": "Šmarje pri Jelšah",
    "GOLOBINJEK - BISTRICA": "Šmarje pri Jelšah",
    "BISTRICA OB SOTLI": "Bistrica ob Sotli",
    "BISTRICA - BIZELJSKO": "Brežice",
    "BIZELJSKO - BREŽICE": "Brežice",
    "BREŽICE - ČATEŽ": "Brežice",
    "ČATEŽ OB SAVI ": "Brežice",
    "KRŠKO - SP.POHANCA": "Krško",
    "SP.POHANCA - BREŽICE": "Brežice",
    "TROJANE - IZLAKE": "Zagorje ob Savi",
    "IZLAKE - ZAGORJE": "Zagorje ob Savi",
    "ZAGORJE - BEVŠKO": "Zagorje ob Savi",
    "BEVŠKO - TRBOVLJE": "Trbovlje",
    "TRBOVLJE - BOBEN - HRASTNIK": "Hrastnik",
    "HRASTNIK - ŠMARJETA": "Hrastnik",
    "ZAGORJE - MOST ČEZ SAVO": "Zagorje ob Savi",
    "BEVSKO - MOST ČEZ SAVO": "Zagorje ob Savi",
    "HRASTNIK - MOST ČEZ SAVO": "Hrastnik",
    "MENGEŠ - DUPLICA": "Mengeš",
    "DUPLICA - KAMNIK": "Kamnik",
    "KAMNIK - MEKINJE": "Kamnik",
    "KAMNIK (MEKINJE) - SP.  STRANJE": "Kamnik",
    "SP. STRANJE - STAHOVICA": "Kamnik",
    "STAHOVICA - ČRNIVEC": "Kamnik",
    "ČRNIVEC - GORNJI GRAD": "Gornji Grad",
    "GORNJI GRAD - RADMIRJE": "Gornji Grad",
    "RADMIRJE - MOZIRJE": "Mozirje",
    "MOZIRJE ": "Mozirje",
    "MOZIRJE - SOTESKA": "Mozirje",
    "SOTESKA - LETUŠ": "Mozirje",
    "LETUŠ - M.BRASLOVČE": "Mozirje",
    "M.BRASLOVČE - PARIŽLJE": "Mozirje",
    "PARIŽLJE - ŠENTRUPERT": "Mozirje",
    "RAVNE - KOTLJE": "Ravne na Koroškem",
    "KOTLJE - STARI TRG": "Ravne na Koroškem",
    "STARI TRG - SLOVENJ GRADEC": "Slovenj Gradec",
    "SPUHLJA - BORL": "Ptuj",
    "BORL - MP ZAVRČ": "Ptuj",
    "PTUJ (BUDINA-CENTER)": "Ptuj",
    "PTUJ - ROGOZNICA": "Ptuj",
    "ROGOZNICA - JANEŽOVCI": "Ptuj",
    "JANEŽOVCI - GOMILCI": "Ptuj",
    "GOMILCI - SENARSKA": "Ptuj",
    "MP G.RADGONA - G.RADGONA": "Gornja Radgona",
    "GORNJA RADGONA - RADENCI": "Gornja Radgona",
    "RADENCI ": "Radenci",
    "RADENCI - VUČJA VAS": "Radenci",
    "VUČJA VAS - KRIŽEVCI": "Ljutomer",
    "KRIŽEVCI ": "Ljutomer",
    "KRIŽEVCI - LJUTOMER": "Ljutomer",
    "LJUTOMER - PAVLOVCI": "Ljutomer",
    "PAVLOVCI - ORMOŽ": "Ormož",
    "PUŠENCI - ORMOŽ": "Ormož",
    "ORMOŽ - MP ORMOŽ": "Ormož",
    "GIBINA - RAZKRIŽJE": "Ljutomer",
    "RAZKRIŽJE - STROČJA VAS": "Ljutomer",
    "STROČJA VAS - LJUTOMER": "Ljutomer",
    "MP HODOŠ - HODOŠ": "Hodoš",
    "HODOŠ - ŠALOVCI": "Hodoš",
    "ŠALOVCI - PETROVCI": "Murska Sobota",
    "PETROVCI - MAČKOVCI": "Murska Sobota",
    "MAČKOVCI - MARTJANCI": "Murska Sobota",
    "MARTJANCI - M.SOBOTA": "Murska Sobota",
    "MURSKA SOBOTA ": "Murska Sobota",
    "MS (PANONSKA ULICA - BAKŠA)": "Murska Sobota",
    "MS (BAKŠA - TOMŠIČEVA ULICA)": "Murska Sobota",
    "MS (TOMŠIČEVA ULICA - PRIKLJUČEK MS)": "Murska Sobota",
    "DRAMLJE - DOLE": "Slovenske Konjice",
    "DOLE - ŠENTJUR": "Šentjur",
    "RADENCI - PETANJCI": "Radenci",
    "PETANJCI - M.SOBOTA(GAJ)": "Murska Sobota",
    "M.SOBOTA(GAJ) - MURSKA SOBOTA": "Murska Sobota",
    "ŽAGA - UČJA": "Bovec",
    "SOLKAN - MOST ČEZ SOČO": "Nova Gorica",
    "SOLKAN MOST - GONJAČE": "Nova Gorica",
    "GONJAČE - DOBROVO": "Nova Gorica",
    "DOBROVO - NEBLO": "Nova Gorica",
    "NEBLO - MP NEBLO": "Nova Gorica",
    "BAČA - KNEŽA": "Tolmin",
    "KNEŽA - PODBRDO": "Tolmin",
    "PODBRDO - PETROVO BRDO": "Tolmin",
    "PETROVO BRDO - PODROŠT": "Tolmin",
    "PODROŠT - ZALI LOG": "Tolmin",
    "ZALI LOG - ČEŠNJICA": "Škofja Loka",
    "ČEŠNJICA - ŠKOFJA LOKA": "Škofja Loka",
    "ŠKOFJA LOKA": "Škofja Loka",
    "PODGRAD - IL.BISTRICA": "Ilirska Bistrica",
    "IL.BISTRICA (VILHARJEVA CESTA)": "Ilirska Bistrica",
    "IL.BISTRICA - PIVKA": "Ilirska Bistrica",
    "DIVAČA - FAMLJE": "Divača",
    "FAMLJE - RIBNICA": "Divača",
    "DEKANI  -  R.ŠKOFIJE": "Koper",
    "R.ŠKOFIJE - KRIŽ.MORETINI": "Koper",
    "KRIŽ.MORETINI - ANKARAN": "Koper",
    "ANKARAN - MP LAZARET": "Koper",
    "GORENJA VAS - LUČINE": "Gorenja Vas",
    "LUČINE - LJUBLJANICA": "Ljubljana",
    "LJUBLJANICA - VRZDENEC": "Ljubljana",
    "VRZDENEC - HORJUL": "Ljubljana",
    "HORJUL - VRHNIKA": "Vrhnika",
    "LOGATEC - ROVTE": "Logatec",
    "ROVTE -  ŽIRI": "Žiri",
    "ŽIRI - TREBIJA": "Žiri",
    "LJ(VIČ) - AC BREZOVICA": "Ljubljana",
    "AC BREZOVICA - BREZOVICA": "Ljubljana",
    "LOGATEC (TRŽAŠKA C.) ": "Logatec",
    "KALCE - PLANINA": "Logatec",
    "PLANINA - RAVBARKOMANDA": "Postojna",
    "RAVBARKOMANDA - PO(R913)": "Postojna",
    "PO(R913) - POSTOJNA": "Postojna",
    "RAZDRTO - SENOŽEČE": "Postojna",
    "SENOŽEČE - DIVAČA": "Divača",
    "DIVAČA - MATAVUN": "Divača",
    "MATAVUN - KOZINA": "Koper",
    "KORTINE  -  RIŽANA": "Koper",
    "RIŽANA - DEKANI": "Koper",
    "DEKANI - PRIKLJ. SRMIN": "Koper",
    "BISTRICA - TRŽIČ": "Tržič",
    "TRŽIČ - GOLNIK": "Tržič",
    "GOLNIK - KOKRICA": "Kranj",
    "KOKRICA - KRANJ": "Kranj",
    "KRANJ Z  -  POLICA": "Kranj",
    "POLICA - NAKLO(MARINŠEK)": "Kranj",
    "NAKLO(MARINŠEK) - PRIKLJ. NAKLO": "Kranj",
    "PRIKLJ. NAKLO - PODTABOR": "Kranj",
    "PODTABOR - GOBOVCE": "Kranj",
    "GOBOVCE - ČRNIVEC": "Kranj",
    "POLICA - KR(KIDRIČEVA)": "Kranj",
    "KRANJ(KIDRIČEVA  -  ISKRA)": "Kranj",
    "KR(ISKRA - LABORE)": "Kranj",
    "MEDVODE - ZBILJE": "Medvode",
    "ZBILJE - VODICE": "Medvode",
    "VODICE - MOSTE": "Ljubljana",
    "MOSTE - DUPLICA": "Kamnik",
    "KAMNIK - TUHINJ": "Kamnik",
    "TUHINJ - LOČICA": "Kamnik",
    "ŽELODNIK - KRTINA": "Domžale",
    "KRTINA - MORAVČE": "Moravče",
    "MORAVČE - DRTIJA": "Moravče",
    "DRTIJA - TRATA": "Moravče",
    "TRATA - IZLAKE": "Zagorje ob Savi",
    "LITIJA - ŠMARTNO": "Litija",
    "ŠMARTNO - GRM": "Litija",
    "GRM - RADOHOVA VAS": "Litija",
    "RADOHOVA VAS - BIČ": "Trebnje",
    "ŠMARTNO PRI LITIJI - M.KOSTREVICA": "Šmartno pri Litiji",
    "M. KOSTREVICA - LJUBEŽ V LAZIH": "Šmartno pri Litiji",
    "LJUBEŽ V LAZIH - MORAVČE": "Moravče",
    "MORAVČE - TIHABOJ-MIRNA": "Moravče",
    "MOKRONOG - ZBURE": "Mokronog",
    "ZBURE - ŠKOCJAN": "Škocjan",
    "ŠKOCJAN - DOBRUŠKA VAS": "Škocjan",
    "DOBRUŠKA V. - ŠENTJERNEJ": "Šentjernej",
    "SOTESKA - STRAŽA": "Novo Mesto",
    "STRAŽA - NM DRSKA": "Novo Mesto",
    "NM DRSKA - NM ŽABJA VAS": "Novo Mesto",
    "NOVO MESTO - RATEŽ": "Novo Mesto",
    "RATEŽ - ŠENTJERNEJ": "Šentjernej",
    "ŠENTJERNEJ - KOSTANJEVICA": "Kostanjevica na Krki",
    "KOSTANJEVICA - KRIŽAJ": "Kostanjevica na Krki",
    "KRIŽAJ - ČATEŽ OB SAVI": "Brežice",
    "BREŽICE - DOBOVA": "Brežice",
    "DOBOVA - M.P. RIGONCE": "Brežice",
    "RUČETNA VAS - ŠTREKLJEVEC": "Črnomelj",
    "ŠTREKLJEVEC - JUGORJE": "Črnomelj",
    "PODSREDA - SENOVO": "Krško",
    "SENOVO - BRESTANICA": "Krško",
    "ŠENTJUR - ČRNOLICA": "Šentjur",
    "ČRNOLICA - LESIČNO": "Šentjur",
    "LESIČNO - ŠONOVO": "Šentjur",
    "ŠONOVO - PODSREDA": "Podsreda",
    "PODSREDA - BISTRICA": "Bistrica ob Sotli",
    "BISTRICA OB SOTLI - MP BISTRICA": "Bistrica ob Sotli",
    "BOŠTANJ - OREŠJE/SEVNICI": "Sevnica",
    "OREŠJE/SEVNICI - PLANINA": "Sevnica",
    "PLANINA - DEŽNO": "Sevnica",
    "DEŽNO - ČRNOLICA": "Sevnica",
    "POLJANA - MEŽICA": "Mežica",
    "MEŽICA - ČRNA": "Mežica",
    "ČRNA - ŠENTVID": "Črna na Koroškem",
    "ŠENTVID - ŠOŠTANJ": "Šoštanj",
    "ŠOŠTANJ - PESJE": "Šoštanj",
    "PESJE - VELENJE": "Velenje",
    "PESJE - GORENJE": "Velenje",
    "GORENJE  -  REČICA": "Velenje",
    " REČICA - LETUŠ": "Velenje",
    "LATKOVA VAS - PREBOLD": "Prebold",
    "PREBOLD - SPODNJE GABRSKO": "Prebold",
    "SPODNJE GABRSKO - TRBOVLJE": "Trbovlje",
    "RADMIRJE - LUČE": "Luče",
    "LUČE - SESTRE LOGAR": "Luče",
    "S.LOGAR - PAVLIČEVO SEDLO": "Luče",
    "VIŠNJA VAS - STRMEC": "Celje",
    "STRMEC - DOBRNA": "Celje",
    "ODCEP V DOBRNO": "Celje",
    "DOBRNA - ČRNOVA": "Celje",
    "PESNICA - PRIKLJ. PESNICA": "Pesnica",
    "PRIKLJ. PESNICA - MARIBOR": "Maribor",
    "MARIBOR - POBREŽJE": "Maribor",
    "POBREŽJE - TABOR": "Maribor",
    "MB (PTUJSKA CESTA) - HOČE": "Maribor",
    "MB (PTUJSKA - STRELIŠKA CESTA)": "Maribor",
    "HOČE  - SLIVNICA": "Hoče",
    "SLIVNICA - FRAM": "Slivnica",
    "FRAM - SL.BISTRICA": "Slovenska Bistrica",
    "ODCEP PRIKLJ. SL. BISTRICA S ": "Slovenska Bistrica",
    "SL.BISTRICA ": "Slovenska Bistrica",
    " SL.BISTRICA - LOŽNICA": "Slovenska Bistrica",
    "LOŽNICA - TEPANJE": "Slovenska Bistrica",
    "TEPANJE - SL.KONJICE": "Slovenske Konjice",
    "SL.KONJICE ": "Slovenske Konjice",
    "SL.KONJICE - DOBRAVA": "Slovenske Konjice",
    "DOBRAVA - STRANICE": "Slovenske Konjice",
    "STRANICE - VIŠNJA VAS": "Slovenske Konjice",
    "VIŠNJA VAS - CELJE AC": "Celje",
    "CELJE AC - CELJE": "Celje",
    "GORNJI DOLIČ - STRANICE": "Velenje",
    "ROGATEC": "Rogatec",
    "ROGATEC - MAJŠPERK": "Majšperk",
    "MAJŠPERK ": "Majšperk",
    "MAJŠPERK - APAŠKI KRIŽ": "Majšperk",
    "APAŠKI KRIŽ  -  KIDRIČEVO": "Kidričevo",
    "SENARSKA - LENART": "Lenart",
    "LENART - KRIŽ. SV.ANA": "Lenart",
    "KRIŽ. SV.ANA - ZG.ŠČAVNICA": "Lenart",
    "ZG.ŠČAVNICA - TRATE": "Gornja Radgona",
    "TRATE - MOST ČEZ MURO": "Gornja Radgona",
    "MOST ČEZ MURO - MP TRATE": "Gornja Radgona",
    "RADLJE - RADELJSKI PRELAZ": "Radlje ob Dravi",
    "MARIBOR - RUŠE": "Maribor",
    "RUŠE - SELNICA": "Ruše",
    "DOLJNA POČEHOVA ": "Maribor",
    "POČEHOVA - ZG.KUNGOTA": "Maribor",
    "ZG.KUNGOTA - JURIJ": "Kungota",
    "ŠENTILJ": "Šentilj",
    "ŠENTILJ - PESNICA": "Šentilj",
    "PESNICA - RONDO POČEHOVA": "Pesnica",
    "ŠENTILJ - TRATE": "Šentilj",
    "TRATE - GORNJA RADGONA": "Gornja Radgona",
    "KOBILJE - DOBROVNIK": "Dobrovnik",
    "DOBROVNIK - RENKOVCI": "Dobrovnik",
    "RENKOVCI - BELTINCI": "Beltinci",
    "BRATONCI - DOKLEŽOVJE": "Murska Sobota",
    "DOKLEŽOVJE - KRIŽEVCI": "Križevci",
    "KRIŽEVCI - ŽIHLAVA": "Križevci",
    "ŽIHLAVA - VIDEM": "Križevci",
    "SV. JURIJ OB ŠČAVNICI - CERKVENJAK": "Sveti Jurij ob Ščavnici",
    "CERKVENJAK - PRIKLJ.CERKVENJAK": "Cerkvenjak",
    "PRIKLJ. CERKVENJAK - SENARSKA": "Cerkvenjak",
    "PETANJCI - GEDEROVCI": "Murska Sobota",
    "GEDEROVCI - SKAKOVCI": "Murska Sobota",
    "SKAKOVCI - CANKOVA": "Murska Sobota",
    "CANKOVA - VEČESLAVCI": "Murska Sobota",
    "VEČESLAVCI - SOTINA": "Murska Sobota",
    "SOTINA - MP KUZMA": "Murska Sobota",
    "MURSKA SOBOTA - VEŠČICA": "Murska Sobota",
    "VEŠČICA - GEDEROVCI": "Murska Sobota",
    "GEDEROVCI - MP GEDEROVCI": "Murska Sobota",
    "MARTJANCI - MORAVSKE TOPLICE": "Murska Sobota",
    "MORAVSKE TOPLICE - DOBROVNIK": "Murska Sobota",
    "DOBROVNIK - RONDO DOLGA VAS": "Dobrovnik",
    "M.SOBOTA - LIPOVCI": "Murska Sobota",
    "LIPOVCI - BRATONCI": "Murska Sobota",
    "BRATONCI - BELTINCI": "Murska Sobota",
    "BELTINCI - ČRENŠOVCI": "Beltinci",
    "ČRENŠOVCI ": "Črenšovci",
    "ČRENŠOVCI - DOL.LAKOŠ": "Črenšovci",
    "DOL. LAKOŠ - LENDAVA": "Lendava",
    "LENDAVA - DOLINA": "Lendava",
    "DOLINA - MP PINCE": "Lendava",
    "RAZDRTO - MANČE": "Vipava",
    "MANČE - VIPAVA": "Vipava",
    "VIPAVA ": "Vipava",
    "AJDOVŠČINA  (OBVOZNICA) ": "Ajdovščina",
    "SELO - TRI HIŠE": "Ajdovščina",
    "TRI HIŠE - AJŠEVICA": "Nova Gorica",
    "AJŠEVICA  -  NOVA GORICA": "Nova Gorica",
    "NOVA GORICA": "Nova Gorica",
    "N.GORICA - ROŽNA DOLINA": "Nova Gorica",
    "SENOŽEČE - ŠTORJE": "Sežana",
    "ŠTORJE - SEŽANA": "Sežana",
    "SEŽANA - FERNETIČI": "Sežana",
    "SEŽANA - DIVAČA": "Sežana",
    "MEDLOG - PETROVČE": "Celje",
    "PETROVČE - ŽALEC": "Žalec",
    "ŽALEC - VRBENSKO POLJE": "Žalec",
    "VRBENSKO POLJE - ŠEMPETER": "Žalec",
    "ŠEMPETER - LATKOVA VAS": "Žalec",
    "LATKOVA VAS - ŠENTRUPERT": "Žalec",
    "ŠENTRUPERT - VRANSKO": "Žalec",
    "VRANSKO - LOČICA": "Vransko",
    "LOČICA - TROJANE": "Vransko",
    "TROJANE - LUKOVICA": "Lukovica",
    "LUKOVICA  -  ŽELODNIK": "Lukovica",
    "ŽELODNIK - DOMŽALE": "Domžale",
    "DOMŽALE - STOB": "Domžale",
    "STOB - TRZIN": "Domžale",
    "IVANČNA GORICA - GRM": "Ivančna Gorica",
    "GRM - PLUSKA": "Novo Mesto",
    "PLUSKA - PRIKLJ. TREBNJE Z": "Trebnje",
    "PRIKLJ. TREBNJE Z - TREBNJE": "Trebnje",
    "GRM - ŠENTJURIJ": "Novo Mesto",
    "ŠENTJURIJ - PRIKLJ. NM ZAHOD": "Novo Mesto",
    "PRIKLJ. NM ZAHOD - LOČNA": "Novo Mesto",
    "NOVO MESTO (LOČNA - MAČKOVEC)": "Novo Mesto",
    "MAČKOVEC - LEŠNICA": "Novo Mesto",
    "LEŠNICA - OTOČEC": "Novo Mesto",
    "OTOČEC - KRONOVO": "Novo Mesto",
    "KRONOVO - DOLENJE KRONOVO": "Novo Mesto",
    "DOLENJE KRONOVO - GOR. GOMILA": "Novo Mesto",
    "GOR.GOMILA - DOBRAVA": "Novo Mesto",
    "PESNICA - LENART": "Pesnica",
    "PRIKLJ. LENART - LENART": "Lenart",
    "LENART - GORNJA RADGONA": "Lenart",
    "GORNJA RADGONA": "Gornja Radgona",
    "HOČE - PRIKLJ.  ROGOZA": "Hoče",
    "PRIKLJ.  ROGOZA - LETALIŠČE MARIBOR": "Maribor",
    "ARJA VAS - ŽALEC": "Celje",
    "HRUŠICA - PLAVŽ": "Jesenice",
    "PLAVŽ - JESENICE": "Jesenice",
    "JESENICE - JAVORNIK": "Jesenice",
    "JAVORNIK - ŽIROVNICA": "Jesenice",
    "ŽIROVNICA - LESCE": "Radovljica",
    "RADOVLJICA - PODVIN": "Radovljica",
    "PODVIN - ČRNIVEC": "Radovljica",
    "MB AC - MIKLAVŽ": "Maribor",
    "MIKLAVŽ - HAJDINA": "Maribor",
    "ZLATOLIČJE – PRIKLJ. ZLATOLIČJE ": "Maribor",
    "HAJDINA  (Mariborska c.- Gomile) ": "Hajdina",
    "ZGORNJE GRUŠKOVJE": "Maribor",
    "BORJANA - PODBELA": "Kobarid",
    "PODBELA - ROBIDIŠČE": "Kobarid",
    "STARO SELO - BREGINJ-MOST": "Kobarid",
    "MOST NA SOČI - UŠNIK": "Tolmin",
    "ROČINJ - LIG": "Nova Gorica",
    "KAMBREŠKO - SOLARJI": "Nova Gorica",
    "SOLARJI - LIVEK": "Nova Gorica",
    "SOLARJI-MEJA ITALIJA": "Nova Gorica",
    "KANAL-LIG-MIŠČEK-NEBLO": "Nova Gorica",
    "PREVAL - GRGAR-ČEPOVAN": "Nova Gorica",
    "SOLKAN - GRGAR": "Nova Gorica",
    "GRGAR - LOKVE": "Nova Gorica",
    "LOKVE - ČEPOVAN": "Nova Gorica",
    "ČEPOVAN - DOL.TREBUŠA": "Idrija",
    "AJDOVŠČINA - PREDMEJA": "Ajdovščina",
    "PREDMEJA - LOKVE": "Ajdovščina",
    "ČEPOVAN - MOST NA SOČI": "Tolmin",
    "D.TREBUŠA - SP.IDRIJA": "Idrija",
    "PEČNIK(MAROF) - ŽIRI": "Žiri",
    "DORNBERK - SELO": "Nova Gorica",
    "PLAVE - GONJAČE": "Nova Gorica",
    "AJŠEVICA - KROMBERK": "Nova Gorica",
    "KROMBERK - NOVA GORICA": "Nova Gorica",
    "PRIKLJ. ŠEMPETER - ŠEMPETER (POLJE)": "Šempeter pri Gorici",
    "ŠEMPETER (POLJE) - VRTOJBA": "Šempeter pri Gorici",
    "VRTOJBA -  D.VRTOJBA": "Šempeter pri Gorici",
    "D.VRTOJBA -  GORNJI MIREN": "Miren-Kostanjevica",
    "GORNJI MIREN - MIREN": "Miren-Kostanjevica",
    "MIREN - OPATJE SELO": "Miren-Kostanjevica",
    "OPATJE SELO - KOMEN": "Komen",
    "KOMEN - KOBJEGLAVA": "Komen",
    "KOBJEGLAVA - ŠTANJEL": "Komen",
    "ŠTANJEL - MANČE": "Vipava",
    "TRI HIŠE - PRIKLJ. VOGRSKO": "Nova Gorica",
    "PRIKLJ.  VOGRSKO - VOLČJA DRAGA": "Nova Gorica",
    "VOLČJA DRAGA - RENČE": "Nova Gorica",
    "RENČE - GORNJI MIREN": "Nova Gorica",
    "GORJANSKO - KLARIČI": "Komen",
    "KOMEN - GORJANSKO": "Komen",
    "GORJANSKO - ŽEKENC": "Komen",
    "BRANIK - KOMEN": "Nova Gorica",
    "KOMEN  - KRAJNA VAS": "Komen",
    "KRAJNA VAS - DUTOVLJE": "Komen",
    "DUTOVLJE - REPENTABOR": "Komen",
    "ŠTORJE - ŠTANJEL": "Sežana",
    "KALCE - PODKRAJ": "Logatec",
    "PODKRAJ - COL": "Logatec",
    "GORIČE - KOŠANA": "Postojna",
    "KOŠANA - KAL": "Postojna",
    "KASTELEC - PODGORJE": "Koper",
    "LOKA - PODPEČ-RAKITOVEC": "Koper",
    "BERTOKI - SV. ANTON": "Koper",
    "SV. ANTON - GRAČIŠČE": "Koper",
    "GRAČIŠČE - BREZOVICA": "Koper",
    "ČRNI KAL  -  OSP": "Koper",
    "SEČOVLJE - DRAGONJA": "Piran",
    "VALETA": "Piran",
    "VALETA - BELI KRIŽ-PIRAN": "Piran",
    "PREM - ČELJE": "Ilirska Bistrica",
    "ČELJE - PREGARJE": "Ilirska Bistrica",
    "PREGARJE - OBROV": "Ilirska Bistrica",
    "OBROV - GOLAC": "Ilirska Bistrica",
    "STAROD - MEJA RH": "Ilirska Bistrica",
    "IL.BISTRICA - ZABIČE": "Ilirska Bistrica",
    "ZABIČE - NOVOKRAČINE": "Ilirska Bistrica",
    "JELŠANE - NOVOKRAČINE": "Ilirska Bistrica",
    "BITNJE - JEREKA": "Kranj",
    "JEREKA - JEZERO": "Kranj",
    "JAVORNIK - GORJE": "Bled",
    "GORJE - BLED": "Bled",
    "BLED (REČICA - SELIŠKA CESTA)": "Bled",
    "LESCE - K.GORICA-LIPNICA": "Radovljica",
    "LIPNICA - KROPA": "Radovljica",
    "KROPA - RUDNO": "Radovljica",
    "RUDNO - ČEŠNJICA": "Radovljica",
    "LIPNICA - OVSIŠE": "Radovljica",
    "OVSIŠE - GOBOVCE": "Radovljica",
    "PODTABOR - ZVIRČE": "Tržič",
    "ŽIROVNICA - BEGUNJE": "Žirovnica",
    "BEGUNJE - BISTRICA(TRŽIČ)": "Tržič",
    "LJ(ŠENTVID - ŠMARTNO)": "Ljubljana",
    "LJ(ŠMARTNO) - VODICE": "Ljubljana",
    "VODICE ": "Vodice",
    "VODICE - SP.BRNIK": "Vodice",
    "SP.BRNIK - CERKLJE": "Cerklje na Gorenjskem",
    "RAKEK - LOGATEC": "Logatec",
    "LJUBLJANICA - POL.GRADEC": "Ljubljana",
    "POL.GRADEC - DOBROVA": "Ljubljana",
    "DOBROVA - LJ(DOLGI MOST)": "Ljubljana",
    "VRHNIKA - PODPEČ": "Vrhnika",
    "PODPEČ - IG": "Ig",
    "IG": "Ig",
    "IG - LJ (PERUZZIJEVA)": "Ljubljana",
    "PODPEČ - RAKITNA": "Brezovica",
    "RAKITNA - CERKNICA": "Cerknica",
    "LJ(ŠMARTIN.) - PRIKLJ. SNEBERJE": "Ljubljana",
    "PRIKLJ. SNEBERJE - ŠENTJAKOB": "Ljubljana",
    "ŠENTJAKOB - DOMŽALE": "Domžale",
    "DOMŽALE - DUPLICA": "Kamnik",
    "LJ(LITIJSKA) - ZADVOR": "Ljubljana",
    "ZADVOR - ŠMARTNO P.LITIJI": "Litija",
    "ŠKOFLJICA  -  ŠMARJE-SAP": "Škofljica",
    "ŠMARJE - SAP - CIKAVA": "Grosuplje",
    "GROSUPLJE - IVANČNA GOR.": "Grosuplje",
    "PEROVO - GROSUPLJE": "Grosuplje",
    "GROSUPLJE": "Grosuplje",
    "GROSUPLJE - MLAČEVO": "Grosuplje",
    "MLAČEVO - PLEŠIVICA": "Grosuplje",
    "PLEŠIVICA - KRKA": "Grosuplje",
    "MLAČEVO - VIDEM": "Grosuplje",
    "VIDEM - RAŠICA": "Grosuplje",
    "VIDEM - PRI CERKVI STRUGE": "Videm",
    "PRI CERKVI STRUGE - ZVIRČE": "Videm",
    "ZVIRČE - SMUKA": "Videm",
    "ZAGRADEC - AMBRUS-ŽVIRČE": "Ambrus",
    "ŽUŽEMBERK - PLUSKA": "Žužemberk",
    "MIRNA PEČ - NOVO MESTO (BUČNA VAS)": "Mirna Peč",
    "NOVO MESTO (BUČNA VAS - KRKA)": "Novo Mesto",
    "PRIKLJ. NM ZAHOD - V. BUČNA VAS": "Novo Mesto",
    "V. BUČNA VAS - NM BUČNA VAS": "Novo Mesto",
    "ŠENTJURIJ-MIRNA PEČ": "Mirna Peč",
    "MORAVČE - ČATEŽ": "Moravče",
    "ČATEŽ - TREBNJE": "Trebnje",
    "SODRAŽICA - HRIB": "Sodražica",
    "HRIB - PODPLANINA": "Sodražica",
    "ŠTALCERJI - KOČ. REKA": "Kočevje",
    "DOL. VAS  -  GOTEN. - KOČ. REKA": "Kočevje",
    "KOČEVSKA REKA - BOROVEC": "Kočevje",
    "BOROVEC  -  DRAGARJI": "Kočevje",
    "DRAGARJI - GOZDNA CESTA (OSILNICA)": "Osilnica",
    "GOZDNA CESTA (OSILNICA) - OSILNICA": "Osilnica",
    "PETRINA - GRIVAC-MIRTOVIČI": "Kočevje",
    "BOSLJIVA LOKA - OSILNICA": "Osilnica",
    "DOBLIČE - SV.ANA-STARI TRG": "Črnomelj",
    "STARI TRG ": "Črnomelj",
    "STARI TRG - BREZOVICA": "Črnomelj",
    "STARI TRG - KOT": "Črnomelj",
    "KOT - SODEVCI": "Črnomelj",
    "ČRNOMELJ (KOČEVJE - VINIŠKA CESTA)": "Črnomelj",
    "ČRNOMELJ - DOLENJCI": "Črnomelj",
    "DOLENJCI - VRHOVCI": "Črnomelj",
    "VRHOVCI - ŽUNIČI": "Črnomelj",
    "ŽUNIČI - MP ŽUNIČI": "Črnomelj",
    "MEJA RH - KRMAČINA - DRAŠIČI": "Metlika",
    "DRAŠIČI - METLIKA": "Metlika",
    "METLIKA - RADOVIČI": "Metlika",
    "RADOVIČI - MP BOŽAKOVO": "Metlika",
    "BUŠINJA VAS - RADOVICA": "Metlika",
    "RADOVICA - OSTRIŽ": "Metlika",
    "GABER -  URŠNA S. - NOVO M.": "Novo Mesto",
    "LJUBEŽ V LAZIH - SOPOTA": "Litija",
    "SOPOTA - RADEČE": "Radeče",
    "SOPOTA - PODKUM-ZAGORJE": "Zagorje ob Savi",
    "ZBURE - ŠMARJEŠKE TOPLICE": "Šmarješke Toplice",
    "ŠMARJEŠKE TOPLICE - DOLENJE KRONOVO": "Šmarješke Toplice",
    "GABRJE - RATEŽ": "Novo Mesto",
    "BIZELJSKO  -  OREŠJE": "Brežice",
    "KRIŽAJ - PODBOČJE-ŠUTNA": "Brežice",
    "ŠUTNA - PLANINA V PODBOČJU": "Brežice",
    "IMPOLJCA - ZAVRATEC": "Krško",
    "ZAVRATEC - SMEDNIK": "Krško",
    "SMEDNIK - ZAMEŠKO-KOSTANJEVICA": "Krško",
    "DRNOVO - KRIŽAJ": "Krško",
    "ZAVRATEC - ŠKOCJAN": "Škocjan",
    "ČATEŽ OB SAVI - MOKRICE": "Brežice",
    "MOKRICE  -  OBREŽJE - SLOV. VAS": "Brežice",
    "SP. POHANCA - (R1-219)": "Brežice",
    "(R1-219) - KAPELE": "Brežice",
    "KAPELE ": "Brežice",
    "KAPELE - RAKOVEC": "Brežice",
    "MP  NOVA VAS - PIŠECE": "Brežice",
    "PIŠECE - ZG.POHANCA-KRŠKO": "Krško",
    "ST.VAS - FIGAROV MOST": "Krško",
    "RADEČE - BREG": "Radeče",
    "BREG - SEVNICA": "Sevnica",
    "SEVNICA - BLANCA": "Sevnica",
    "BLANCA - BRESTANICA": "Krško",
    "RIMSKE TOPLICE - JURKLOŠTER": "Laško",
    "JURKLOŠTER - DEŽNO": "Laško",
    "LAŠKO ": "Laško",
    "LAŠKO - BREZE-ŠENTJUR": "Šentjur",
    "ŠENTJUR(PODGORA - NOVA V)": "Šentjur",
    "LOKE - LEDINŠČICA": "Šentjur",
    "LESIČNO - GOLOBINJEK": "Šentjur",
    "IMENO - MP IMENO": "Šentjur",
    "PRELASKO - BUČE-KOZJE": "Kozje",
    "TEKAČEVO - ROGAŠKA SLAT.": "Rogaška Slatina",
    "RODNE - MP RAJNKOVEC": "Rogaška Slatina",
    "TEPANJE - ŽIČE": "Slovenske Konjice",
    "ŽIČE - KARTUZIJA": "Slovenske Konjice",
    "KARTUZIJA - DRAMLJE": "Slovenske Konjice",
    "DOLE - PONIKVA-LOČE": "Slovenske Konjice",
    "SLOV.KONJICE - ŽIČE": "Slovenske Konjice",
    "ŽIČE ": "Slovenske Konjice",
    "ŽIČE - MLAČE": "Slovenske Konjice",
    "MLAČE - POLJČANE": "Poljčane",
    "POLJČANE - MAJŠPERK": "Poljčane",
    "PODLEHNIK - KOZMINCI": "Ptuj",
    "KOZMINCI-ŽETALE - ROGATEC": "Rogatec",
    "MAJŠPERK - JUROVCI": "Majšperk",
    "TRŽEC - VIDEM": "Videm",
    "VIDEM - ZG. LESKOVEC": "Videm",
    "ZAVRČ - DRENOVEC": "Zavrč",
    "BORL-CIRKULANE - MP MEJE": "Cirkulane",
    "NOVA CERKEV - SOCKA-VITANJE": "Vitanje",
    "VELENJE - POLZELA": "Velenje",
    "POLZELA - DOBRTEŠA VAS": "Polzela",
    "POLZELA ": "Polzela",
    "POLZELA - REČICA": "Polzela",
    "GORENJE - SOTESKA": "Velenje",
    "VELENJE - ŠKALE": "Velenje",
    "ŠKALE - GRAŠKA  G.-ŠMIKLA": "Velenje",
    "SL.GRADEC - MISL.DOBRAVA": "Slovenj Gradec",
    "NAZARJE - GORNJI GRAD": "Nazarje",
    "MEŽICA - REHT": "Mežica",
    "DRAVOGRAD - ČRNEČE": "Dravograd",
    "ČRNEČE - MP LIBELIČE": "Dravograd",
    "SL.KONJICE - OPLOTNICA": "Slovenske Konjice",
    "OPLOTNICA - LOŽNICA": "Oplotnica",
    "RUTA - LOVRENC": "Lovrenc na Pohorju",
    "LOVRENC - PESEK": "Lovrenc na Pohorju",
    "PESEK - ROGLA": "Zreče",
    "ROGLA - ZREČE": "Zreče",
    "ZREČE - ZEČE": "Zreče",
    "DRAVOGRAD - TRBONJE": "Dravograd",
    "TRBONJE - GORTINA": "Dravograd",
    "TRBONJE - VUZENICA": "Vuzenica",
    "VUZENICA - VUHRED": "Vuzenica",
    "MUTA ": "Muta",
    "MUTA - GORTINA": "Muta",
    "GORTINA - BISTRIŠKI JAREK": "Muta",
    "RADLJE - RIBNICA": "Radlje ob Dravi",
    "RIBNICA - BREZNO": "Radlje ob Dravi",
    "RUŠE - PUŠČAVA": "Ruše",
    "OŽBALT - ZG. KAPLA": "Radlje ob Dravi",
    "HAJDIČEV MLIN - GRADIŠČE": "Slovenska Bistrica",
    "SP.SELNICA - DUH NA OSTREM VRHU": "Slovenska Bistrica",
    "ZG.KUNGOTA - MP PLAČ": "Kungota",
    "MB (MELJSKA CESTA)": "Maribor",
    "MB (MALEČNIK-most) - MB (MALEČNIK)": "Maribor",
    "MB (MALEČNIK) - PERNICA": "Maribor",
    "PERNICA - PRIKLJ. PERNICA": "Maribor",
    "MARIBOR - DVORJANE": "Maribor",
    "DVORJANE - PTUJ": "Ptuj",
    "PTUJ - HAJDINA": "Ptuj",
    "HAJDINA - TURNIŠČE": "Ptuj",
    "FRAM - RAČE": "Rače",
    "RAČE ": "Rače",
    "RAČE - KUNGOTA-KIDRIČEVO": "Rače",
    "ŽIHLAVA - JURŠINCI": "Juršinci",
    "JURŠINCI - GABERNIK": "Juršinci",
    "GABERNIK - ROGOZNICA(PTUJ)": "Ptuj",
    "LJUTOMER - DORNAVA": "Ljutomer",
    "DORNAVA - KRIŽ.SPUHLJA": "Dornava",
    "KRIŽ.SPUHLJA - PTUJ": "Ptuj",
    "SV. JURIJ OB ŠČAVNICI - GRABONOŠ": "Sveti Jurij ob Ščavnici",
    "GRABONOŠ - SP. IVANJCI": "Gornja Radgona",
    "SP.IVANJCI - GORNJA RADGONA": "Gornja Radgona",
    "M.SOBOTA - GORICA": "Murska Sobota",
    "GORICA - LEMERJE": "Murska Sobota",
    "LEMERJE - SKAKOVCI": "Murska Sobota",
    "LEMERJE - GRAD": "Murska Sobota",
    "GRAD ": "Murska Sobota",
    "GRAD - KUZMA": "Kuzma",
    "CANKOVA ": "Cankova",
    "CANKOVA - GERLINCI": "Cankova",
    "KOROVCI ": "Cankova",
    "GERLINCI": "Cankova",
    "PERTOČA - FIKŠINCI": "Murska Sobota",
    "FIKŠINCI ": "Murska Sobota",
    "ROGAŠOVCI - KRAMAROVCI": "Rogašovci",
    "KRAMAROVCI": "Rogašovci",
    "SOTINA": "Rogašovci",
    "PETROVCI - MARTINJE": "Murska Sobota",
    "MARTINJE -  KUZMA": "Kuzma",
    "KUZMA - MP KUZMA": "Kuzma",
    "MP MARTINJE - MARTINJE": "Kuzma",
    "ŠALOVCI - ČEPINCI": "Šalovci",
    "ČEPINCI - MEJA MADŽARSKA": "Šalovci",
    "HODOŠ - DOMANJŠEVCI": "Hodoš",
    "DOMANJŠEVCI ": "Hodoš",
    "DOMANJŠEVCI - BERKOVCI": "Hodoš",
    "BERKOVCI - KOBILJE": "Hodoš",
    "MARTJANCI - SEBEBORCI": "Murska Sobota",
    "SEBEBORCI - TRAKŠAROV BREG": "Murska Sobota",
    "TRAKŠAROV BREG -  FOKOVCI": "Murska Sobota",
    "FOKOVCI - PROSENJAKOVCI": "Murska Sobota",
    "RENKOVCI - ČRENŠOVCI": "Črenšovci",
    "ČRENŠOVCI - RAZKRIŽJE": "Črenšovci",
    "STROČJA VAS - PAVLOVCI": "Ljutomer",
    "RAZKRIŽJE - MEJA RH": "Ljutomer",
    "ŠKOFLJICA - IG": "Škofljica",
    "IG - IŠKA VAS": "Ig",
    "IŠKA VAS - KRIM": "Ig",
    "KRIM - RAKITNA": "Brezovica",
    "HOTIZA - VELIKA POLANA": "Lendava",
    "VELIKA POLANA - LIPA-BELTINCI": "Beltinci",
    "ŽICE - SV. ANA-ZG. ŠČAVNICA": "Sveti Jurij ob Ščavnici",
    "ZG.ŠČAVNICA - DRAŽEN VRH": "Sveti Jurij ob Ščavnici",
    "POLZELA - PARIŽLJE": "Polzela",
    "PARIŽLJE - BRASLOVČE-M.BRASLOVČE": "Braslovče",
    "PONDOR - TABOR": "Tabor",
    "TABOR - OJSTRIŠKA VAS-KAPLA": "Tabor",
    "VAVTA VAS - DOL.TOPLICE": "Novo Mesto",
    "DOL.TOPLICE - PODTURN": "Novo Mesto",
    "CERKVENJAK - VITOMARCI": "Cerkvenjak",
    "VITOMARCI - GABRNIK": "Cerkvenjak",
    "MUTA - VUZENICA": "Muta",
    "RAČE - ŠIKOLE": "Rače",
    "TRŽIŠČE - HOTEMEŽ": "Krško",
    "JANEŽOVSKI VRH - DESTRNIK": "Desternik",
    "DESTRNIK - GOMILCI": "Desternik",
    "ŠKOFIJE MEJNI PREHOD": "Koper",
    "ŠKOFIJE MEJNI PREHOD  -  ŠKOFIJE": "Koper",
    "ŠKOFIJE - R.ŠKOFIJE": "Koper",
    "DEKANI - PRIKLJ. LUKA KOPER": "Koper",
    "BERTOKI – KP (ŠKOCJAN)": "Koper",
    "PODPEČ - VNANJE GORICE": "Ljubljana",
    "VNANJE GORICE - BREZOVICA": "Ljubljana",
    "ŠTORE - LAŠKA VAS": "Štore",
    "LAŠKA VAS  -  SVETINA": "Štore",
    "SVETINA  -  BRSTNIK": "Štore",
    "BRSTNIK  -  LAŠKO": "Laško",
    "JANEŽOVCI - DOLGE NJIVE": "Ptuj",
    "DOLGE NJIVE - SPODNJI DUPLEK": "Ptuj",
    "STARI TRG - LOŠKI POTOK": "Loški Potok",
    "LENART - SVETA TROJICA": "Lenart",
    "SV. TROJICA-COGETINCI - SP.IVANJCI": "Sveta Trojica",
    "VELIKE LAŠČE - M SLEVICA": "Velike Lašče",
    "M SLEVICA - LUŽARJI": "Velike Lašče",
    "LUŽARJI - NOVA VAS": "Velike Lašče",
    "VOSEK - JUROVSKI DOL": "Jurovski Dol",
    "JUROVSKI DOL - LENART": "Jurovski Dol",
    "SLOVENSKA VAS - ŠENTRUPERT": "Trebnje",
    "NIZKA - REČICA OB SAVINJI": "Rečica ob Savinji",
    "ARCLIN - LJUBEČNA": "Celje",
    "LJUBEČNA - BUKOVŽLAK": "Celje",
    "BUKOVŽLAK - TEHARJE": "Celje",
    "VOLČE - SOLARJI": "Tolmin",
    "PLANINA-UNEC": "Postojna",
    "RATEČE - PLANICA": "Kranjska Gora",
    "STRMEC - MANGART": "Bovec",
    "IDRSKO - LIVEK": "Kobarid",
    "JEZERO - ZLATOROG": "Bohinj",
    "ZLATOROG - SAVICA": "Bohinj",
    "GORJE - KRNICA": "Bled",
    "KRNICA - ZATRNIK": "Bled",
    "ZATRNIK - MRZLI STUDENEC": "Bled",
    "MRZLI STUDENEC - JEREKA": "Bled",
    "MRZLI STUD. - RUDNO POLJE": "Bohinj",
    "KRNICA - ZG.RADOVNA": "Kranjska Gora",
    "ZG.RADOVNA - DOVJE": "Kranjska Gora",
    "KRAJE - MOJSTRANA": "Kranjska Gora",
    "MOJSTRANA - VRATA": "Kranjska Gora",
    "BOH.BISTRICA - VRESJE": "Bohinj",
    "VRESJE - SORICA": "Železniki",
    "SORICA - PETROVO BRDO": "Železniki",
    "SORICA - PODROŠT": "Železniki",
    "RUDNO - ROVTARICA": "Gorenja vas",
    "ROVTARICA - VRESJE": "Gorenja vas",
    "ZALI LOG - DAVČA": "Železniki",
    "DAVČA - NOVAKI": "Cerkno",
    "NOVAKI - CERKNO": "Cerkno",
    "POSTOJNA - RAKOV.ŠKOC.": "Postojna",
    "RAKOV ŠKOCJAN - PODSKRAJNIK": "Cerknica",
    "IL.BISTRICA (DO PODGRAJSKE UL.)": "Ilirska Bistrica",
    "IL.BISTRICA - GRDA DRAGA": "Ilirska Bistrica",
    "GRDA DRAGA -  PUDOB": "Ilirska Bistrica",
    "DRAGARJI - MEDVEDJEK-DRAGA": "Kočevje",
    "KOČEVJE - ŽELJNE": "Kočevje",
    "ŽELJNE - ROG-BAZA-PODTURN": "Kočevje",
    "KOT - GRGELJ": "Kočevje",
    "GRGELJ - FARA": "Kočevje",
    "PODZEMELJ - DOLENJCI": "Metlika",
    "ŽUNIČI - VINICA": "Črnomelj",
    "VINICA - STARI TRG": "Črnomelj",
    "GABRJE - TRDINOV VRH": "Trebnje",
    "KANDRŠE - VAČE-SP.HOTIČ": "Litija",
    "STAHOVICA - KAM.BISTRICA": "Kamnik",
    "PODLOM - KR.RAK": "Luče",
    "KR.RAK - LUČE": "Luče",
    "SOLČAVA - PODOLŠEVA-SLEME": "Solčava",
    "SLEME - KOPRIVNA": "Solčava",
    "KOPRIVNA - ČRNA": "Črna na Koroškem",
    "ŽIBOVT - SV.DUH-PODOLŠEVA": "Solčava",
    "MOZIRJE - GOLTE": "Mozirje",
    "SP.HOČE - ZG.HOČE": "Hoče",
    "ZG. HOČE - POHORSKA VZPENJAČA": "Hoče",
    "ODCEP ZA AREH ": "Hoče",
    "AREH-ŠUMIK - OSANKARICA-LUKANJA": "Pohorje",
    "PESEK - LUKANJA": "Zreče",
    "LUKANJA - OPLOTNICA": "Oplotnica",
    "RIBNICA - RIBNIŠKA KOČA": "Ribnica na Pohorju",
    "SL.GRADEC - SPOLE": "Slovenj Gradec",
    "SPOLE - PUNGART": "Slovenj Gradec",
    "BREG  -  LISCA": "Sevnica",
    "LISCA - JURKLOŠTER": "Laško",
    "SEŽANA - LIPICA": "Sežana",
    "LIPICA - LOKEV": "Sežana",
    "FRAM - KOPIVNIK": "Fram",
    "KOPIVNIK - CESTNIK-AREH": "Fram",
    "COL - PREDMEJA": "Ajdovščina",
    "BRESTRNICA - GAJ-SV. JURIJ": "Maribor",
    "ČERMOŠNJICE - KOMARNA V.-GRIČICE": "Metlika",
    "MATAVUN - VREME": "Divača",
    "ZAVRHEK - ARTVIŽE": "Divača",
    "ARTVIŽE - PREGARJE": "Ilirska Bistrica",
    "PREGARJE - HARIJE": "Ilirska Bistrica",
    "GRABONOŠ - RADENCI": "Radenci"
};

// Example usage:
console.log(trafficSections["DRAGUČOVA - MB (ZRKOVSKA)"]); // Outputs: Maribor
